apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: tmpwatch-controller
  name: tmpwatch-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tmpwatch-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tmpwatch-controller
    spec:
      containers:
        - image: ghcr.io/draveness/tmpwatch-controller:v0.2.0
          name: tmpwatch-controller
          resources:
            requests:
              cpu: "0"
          volumeMounts:
            - mountPath: /tmp/
              name: tmp-volume
      volumes:
        - name: tmp-volume
          hostPath:
            path: /tmp/
      restartPolicy: Always
